server:
  port: 8080
  servlet:
    context-path: /

mybatis-plus:
  mapper-locations: classpath*:com/example/demo/mapper/*.xml
  type-aliases-package: com.example.demo.pojo

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.201.235.107:3306/shop
    username: root
    password: 123456
  redis:
    host: 101.201.235.107
    port: 6379
    jedis:
      pool:
        max-idle: 20
        max-total: 50
  data:
    mongodb:
      host: 101.201.235.107
      port: 27017

  kafka:
    bootstrap-servers: 101.201.235.107:9092 #指定kafka server的地址，集群配多个，中间，逗号隔开
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: default_consumer_group #群组ID
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

