server:
  port: 8080
  servlet:
    context-path: /

mybatis-plus:
  mapper-locations: classpath*:mybatis-mapper/*.xml
  type-aliases-package: com.example.demo.pojo

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.201.235.107:3306/shop
    username: root
    password: 123456
  redis:
    host: 101.201.235.107
    port: 6379
    jedis:
      pool:
        max-idle: 20
        max-total: 50
  data:
    mongodb:
      host: 101.201.235.107
      port: 27017



